spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/web;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true -> system.out 으로 보여주는 조건이기 때문에 사용 X
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace